# ===========================================================
# CONFIGURACION - MSPRODUCTOS
# ===========================================================

spring:
  application:
    name: msproductos

  # ==========================
  # MYSQL (Laragon)
  # ==========================
  datasource:
    url: jdbc:mysql://localhost:3306/msproductos?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ==========================
  # JPA
  # ==========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Puerto del microservicio
server:
  port: 8082
